name: Build App and Deploy to Aliyun
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      # 第一步 检测代码
      - name: Checkout code
        uses: actions/checkout@v2
      # 第二步 设置node版本
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # 第三步 安装依赖
      - name: Install npm dependencies
        run: npm install
      # 第四步 打包
      - name: Run ${{ vars.NPM_RUN }} task
        run: npm run ${{ vars.NPM_RUN }}
      # 第四步 上传至阿里云
      - name: Deploy to Aliyun
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.USER_HOST }}
          user: ${{ secrets.USER_NAME }}
          pass: ${{ secrets.USER_PASS }}
          connect_timeout: 10s
          local: './dist/*'
          remote: /home/app/web/vue3
